### ISSUE TITLE
What a significant improvement!

### ISSUE THREAD

**Issue by sishenyihuba** [ssamadgh/Ray-Wenderlich-Tutorial-and-Advanced-Operation#1]
What a significant improvement!

Hi,@ssamadhg, I came along with Ray - Tutorial with Operations.

Then, I meet your repo ,find that there has been a better way with  Advanced-Operation.

But,a little difficult . Would u post one tutorial with your improvements with  Advanced-Operation.   

Just Thanks.

**Comment by ssamadgh** [comment]
Hi, and thanks for your message.
Advanced Operation is a wrapper on the common operation and yes it's a little difficult to learn.
I recommend you watch apple WWDC video which I put the link in the intro of the repo.
And the best way to make a better understand of Advanced Operation is just rewrite the sample project.
You can use my project or the one that is linked in WWDC.
With regard

**Comment by sishenyihuba** [comment]
Thanks  for your reply!
I will try my best to learn how this magic happen. First step: watch the WWDC session.💪
sincerely regard
